// Map slider values to years
const yearMap = {
  1: "2500BC",
  2: "2000BC",
  3: "1500BC",
  4: "1000BC",
  5: "800BC",
  6: "600BC",
  7: "400BC",
  8: "200BC",
  9: "1AD",
  10: "100AD",
  11: "200AD",
  12: "300AD",
  13: "400AD",
  14: "500AD",
  15: "600AD",
  16: "700AD",
  17: "800AD",
};

// Initialize the map
const map = L.map("map").setView([50, 25], 4); // Centered on Europe

// Add tile layer to map
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
  attribution: "&copy; OpenStreetMap contributors",
}).addTo(map);

// Define markers data for each time period
const markersData = {
  "2500BC": [
    {
      lat: 58.5106,
      lon: 42.3848,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Finno-Ugric Languages",
    },
    {
      lat: 49.2953,
      lon: 23.5024,
      language: "Indo-European",
      region: "Eastern Europe",
      notes: "Ancestor to the Balto-Slavic Languages",
    },
    {
      lat: 44.5957,
      lon: 25.1554,
      language: "Indo-European",
      region: "Balkans",
      notes: "Ancestor to the Balkan Languages",
    },
    {
      lat: 49.5527,
      lon: 11.2347,
      language: "Indo-European",
      region: "Central Europe",
      notes: "Ancestor to the Germanic and Celt-Italic Languages",
    },
    {
      lat: 38.572,
      lon: 32.5238,
      language: "Indo-European",
      region: "Anatolia",
      notes: "Ancestor to the Anatolian Languages",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Paleo-European",
      region: "Iberian Peninsula, Gaul, Britian, Ireland",
      notes: "",
    },
    {
      lat: 59.2311,
      lon: 29.0612,
      language: "Paleo-European",
      region: "Baltic Europe",
      notes: "",
    },
    {
      lat: 42.1829,
      lon: 12.5507,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "2000BC": [
    {
      lat: 58.5106,
      lon: 42.3848,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Finno-Ugric Languages",
    },
    {
      lat: 49.2953,
      lon: 23.5024,
      language: "Indo-European",
      region: "Eastern Europe",
      notes: "Ancestor to the Balto-Slavic Languages",
    },
    {
      lat: 43.5823,
      lon: 16.4219,
      language: "Indo-European",
      region: "Balkans",
      notes: "Ancestor to the Albandoid(?) Languages",
    },
    {
      lat: 44.061,
      lon: 25.1558,
      language: "Indo-European",
      region: "Balkans",
      notes: "Dacian",
    },
    {
      lat: 40.4148,
      lon: 20.3912,
      language: "Hellenic",
      region: "Balkans",
      notes: "Ancestor to the Western Greek Languages",
    },
    {
      lat: 38.2857,
      lon: 22.4806,
      language: "Hellenic",
      region: "Balkans",
      notes: "Ancestor to the Eastern Greek Languages",
    },
    {
      lat: 49.5527,
      lon: 11.2347,
      language: "Indo-European",
      region: "Central Europe",
      notes: "Ancestor to the Germanic and Celt-Italic Languages",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Hittite",
    },
    {
      lat: 39.4201,
      lon: 27.373,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Proto-Lydian",
    },
    {
      lat: 37.2327,
      lon: 34.1258,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwic",
    },
    {
      lat: 41.03,
      lon: 31.4927,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Palaic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Paleo-European",
      region: "Iberian Peninsula, Gaul, Britian, Ireland",
      notes: "",
    },
    {
      lat: 59.2311,
      lon: 29.0612,
      language: "Paleo-European",
      region: "Baltic Europe",
      notes: "",
    },
    {
      lat: 42.1829,
      lon: 12.5507,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "1500BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans",
      notes: "Western Greek",
    },
    {
      lat: 37.4556,
      lon: 22.4702,
      language: "Hellenic",
      region: "Balkans",
      notes: "Eastern Greek",
    },
    {
      lat: 39.1021,
      lon: 22.2848,
      language: "Hellenic",
      region: "Balkans",
      notes: "Central Greek",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Hittite",
    },
    {
      lat: 39.4201,
      lon: 27.373,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Proto-Lydian",
    },
    {
      lat: 37.2327,
      lon: 34.1258,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwic",
    },
    {
      lat: 41.03,
      lon: 31.4927,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Palaic",
    },
    {
      lat: 46.3644,
      lon: 13.4428,
      language: "Italic",
      region: "",
      notes: "Ancestor to all Italic/Romance languages",
    },
    {
      lat: 47.243,
      lon: 5.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Ancestor to all Celtic languages.",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 41.0734,
      lon: -2.1728,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 42.3848,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Finno-Ugric Languages",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Paleo-European",
      region: "Iberian Peninsula, Gaul, Britian, Ireland",
      notes: "",
    },
    {
      lat: 59.2311,
      lon: 29.0612,
      language: "Paleo-European",
      region: "Baltic Europe",
      notes: "",
    },
    {
      lat: 42.1829,
      lon: 12.5507,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "1000BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans",
      notes: "Western Greek",
    },
    {
      lat: 37.4556,
      lon: 22.4702,
      language: "Hellenic",
      region: "Balkans",
      notes: "Eastern Greek",
    },
    {
      lat: 39.1021,
      lon: 22.2848,
      language: "Hellenic",
      region: "Balkans",
      notes: "Central Greek",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "",
      notes: "Ancestor to all Italic/Romance languages",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Ancestor to all Celtic languages.",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 40.581,
      lon: -5.4929,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Permic Languages",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Paleo-European",
      region: "Iberian Peninsula, Gaul, Britian, Ireland",
      notes: "",
    },
    {
      lat: 42.1829,
      lon: 12.5507,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "800BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans",
      notes: "Western Doric",
    },
    {
      lat: 40.4057,
      lon: 20.5258,
      language: "Hellenic",
      region: "Balkans",
      notes: "Macedonian",
    },
    {
      lat: 39.1311,
      lon: 22.3411,
      language: "Hellenic",
      region: "Balkans, Anatolia",
      notes: "Aeolic",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian",
      notes: "Ionic",
    },
    {
      lat: 37.3118,
      lon: 21.5711,
      language: "Hellenic",
      region: "Balkans, Cyprus",
      notes: "Arcadocypriot",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "Italy",
      notes: "Venetic",
    },
    {
      lat: 42.2948,
      lon: 13.5312,
      language: "Italic",
      region: "Italy",
      notes: "Italic languages",
    },
    {
      lat: 50.5843,
      lon: 0.2126,
      language: "Celtic",
      region: "Britian, Ireland, Gaul, Iberia",
      notes: "Ancestor to Insular Celtic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Ancestor to Contenental Celtic languages.",
    },
    {
      lat: 45.1255,
      lon: 8.3215,
      language: "Celtic",
      region: "South Europe",
      notes: "Lepontic",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 40.581,
      lon: -5.4929,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Permic Languages",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Paleo-European",
      region: "Iberian Peninsula, Gaul, Britian, Ireland",
      notes: "",
    },
    {
      lat: 42.1829,
      lon: 12.5507,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "600BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans, Italy",
      notes: "Western Doric",
    },
    {
      lat: 40.4057,
      lon: 20.5258,
      language: "Hellenic",
      region: "Balkans",
      notes: "Macedonian",
    },
    {
      lat: 39.1311,
      lon: 22.3411,
      language: "Hellenic",
      region: "Balkans, Anatolia",
      notes: "Aeolic",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly, Africa",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy",
      notes: "Ionic",
    },
    {
      lat: 37.3118,
      lon: 21.5711,
      language: "Hellenic",
      region: "Balkans, Cyprus",
      notes: "Arcadocypriot",
    },
    {
      lat: 36.4202,
      lon: 31.47,
      language: "Hellenic",
      region: "Anatolia",
      notes: "Pamphylian",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Luwian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 37.1507,
      lon: 29.4859,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Milyan",
    },
    {
      lat: 37.0223,
      lon: 33.2221,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Sidetic",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "Italy",
      notes: "Venetic",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Latino-Faliscan",
    },
    {
      lat: 42.2948,
      lon: 13.5312,
      language: "Italic",
      region: "Italy",
      notes: "Osco-Umbrian",
    },
    {
      lat: 37.3541,
      lon: 14.3639,
      language: "Italic",
      region: "Sicely",
      notes: "Sicel",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian, Ireland, Gaul, Iberia",
      notes: "Ancestor to Insular Celtic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain",
      notes: "Ancestor to Contenental Celtic languages.",
    },
    {
      lat: 45.1255,
      lon: 8.3215,
      language: "Celtic",
      region: "South Europe",
      notes: "Lepontic",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania, Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 40.581,
      lon: -5.4929,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Permic Languages",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 40.4637,
      lon: -3.7492,
      language: "Paleo-European",
      region: "Iberian Peninsula, Gaul, Britian, Ireland",
      notes: "",
    },
    {
      lat: 43.3613,
      lon: 10.5103,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "400BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans, Italy",
      notes: "Western Doric",
    },
    {
      lat: 40.4057,
      lon: 20.5258,
      language: "Hellenic",
      region: "Balkans",
      notes: "Macedonian",
    },
    {
      lat: 39.1311,
      lon: 22.3411,
      language: "Hellenic",
      region: "Balkans, Anatolia",
      notes: "Aeolic",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly, Africa",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Gaul, Iberia, Eastern Europe",
      notes: "Ionic-Attic",
    },
    {
      lat: 37.3118,
      lon: 21.5711,
      language: "Hellenic",
      region: "Balkans, Cyprus",
      notes: "Arcadocypriot",
    },
    {
      lat: 36.4202,
      lon: 31.47,
      language: "Hellenic",
      region: "Anatolia",
      notes: "Pamphylian",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 37.1507,
      lon: 29.4859,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Milyan",
    },
    {
      lat: 37.0223,
      lon: 33.2221,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Sidetic",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "Italy",
      notes: "Venetic",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Latin",
    },
    {
      lat: 42.385,
      lon: 12.0906,
      language: "Italic",
      region: "Italy",
      notes: "Faliscan",
    },
    {
      lat: 41.1115,
      lon: 15.2631,
      language: "Italic",
      region: "Italy",
      notes: "Oscan",
    },
    {
      lat: 43.2355,
      lon: 13.0018,
      language: "Italic",
      region: "Italy",
      notes: "Umbrian",
    },
    {
      lat: 37.3541,
      lon: 14.3639,
      language: "Italic",
      region: "Sicely",
      notes: "Sicel",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian, Ireland, Iberia",
      notes: "Ancestor to Insular Celtic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain, Iberia, Central Europe",
      notes: "Ancestor to Contenental Celtic languages.",
    },
    {
      lat: 45.1255,
      lon: 8.3215,
      language: "Celtic",
      region: "South Europe",
      notes: "Lepontic",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Germania, Scandenavia",
      notes: "Ancestor to all Germanic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 40.581,
      lon: -5.4929,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Volgaic Languages",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 38.0149,
      lon: -2.3132,
      language: "Paleo-European",
      region: "Iberian Peninsula, Britian",
      notes: "",
    },
    {
      lat: 43.3613,
      lon: 10.5103,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "200BC": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans, Italy",
      notes: "Western Doric",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly, Africa",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Gaul, Iberia, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 37.3118,
      lon: 21.5711,
      language: "Hellenic",
      region: "Balkans",
      notes: "Arcadocypriot",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 38.391,
      lon: 28.1158,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lydian",
    },
    {
      lat: 37.1824,
      lon: 27.5149,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Carian",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 45.3644,
      lon: 12.4428,
      language: "Italic",
      region: "Italy",
      notes: "Venetic",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Latin",
    },
    {
      lat: 42.385,
      lon: 12.0906,
      language: "Italic",
      region: "Italy",
      notes: "Faliscan",
    },
    {
      lat: 41.1115,
      lon: 15.2631,
      language: "Italic",
      region: "Italy",
      notes: "Oscan",
    },
    {
      lat: 43.2355,
      lon: 13.0018,
      language: "Italic",
      region: "Italy",
      notes: "Umbrian",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Brythonic languages.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 40.1729,
      lon: -4.4709,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 43.0204,
      lon: -7.223,
      language: "Celtic",
      region: "Iberia",
      notes: "Gallcian language.",
    },
    {
      lat: 45.1255,
      lon: 8.3215,
      language: "Celtic",
      region: "South Europe",
      notes: "Lepontic",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Central Europe",
      notes: "West Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe",
      notes: "East Germanic Lanuages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "North Germanic Languages",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 40.581,
      lon: -5.4929,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Finno-Volgaic Languages",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 38.0149,
      lon: -2.3132,
      language: "Paleo-European",
      region: "Iberian Peninsula, Britian",
      notes: "",
    },
    {
      lat: 43.3613,
      lon: 10.5103,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "1AD": [
    {
      lat: 40.0016,
      lon: 20.4451,
      language: "Hellenic",
      region: "Balkans, Italy",
      notes: "Western Doric",
    },
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Gaul, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 36.2713,
      lon: 29.424,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Lycian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 45.0302,
      lon: 10.1812,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa",
      notes: "Vulgar Latin",
    },
    {
      lat: 41.1115,
      lon: 15.2631,
      language: "Italic",
      region: "Italy",
      notes: "Oscan",
    },
    {
      lat: 53.1,
      lon: 10.2,
      language: "Germanic",
      region: "Central Europe",
      notes: "West Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe",
      notes: "East Germanic Lanuages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "North Germanic Languages",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian, Gaul, Iberia",
      notes: "Brythonic languages.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 40.1729,
      lon: -4.4709,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 43.0204,
      lon: -7.223,
      language: "Celtic",
      region: "Iberia",
      notes: "Gallcian language.",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 40.581,
      lon: -5.4929,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula, Britian",
      notes: "",
    },
    {
      lat: 43.3613,
      lon: 10.5103,
      language: "Paleo-European",
      region: "Italy",
      notes: "",
    },
  ],
  "100AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Gaul, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe",
      notes: "East Germanic Lanuages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "North Germanic Languages",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Brythonic languages.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 40.1729,
      lon: -4.4709,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 43.0204,
      lon: -7.223,
      language: "Celtic",
      region: "Iberia",
      notes: "Gallcian language.",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 40.581,
      lon: -5.4929,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula, Britian",
      notes: "",
    },
  ],
  "200AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 37.2607,
      lon: 31.0311,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Pisidian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Brythonic languages.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 40.1729,
      lon: -4.4709,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 43.0204,
      lon: -7.223,
      language: "Celtic",
      region: "Iberia",
      notes: "Gallcian language.",
    },
    {
      lat: 48.0445,
      lon: 15.132,
      language: "Celtic",
      region: "Central Europe",
      notes: "Noric",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 40.581,
      lon: -5.4929,
      language: "Lusitanian",
      region: "Iberia",
      notes: "",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula, Britian",
      notes: "",
    },
  ],
  "300AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 41.4623,
      lon: -5.2719,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe, Central Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula, Britian",
      notes: "",
    },
  ],
  "400AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region:
        "Balkans, Anatolian, Italy, Eastern Europe, Middle East, Central Asia",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Classical Latin",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe, Southern Europe, Iberia, Africa",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul, Britain, Central Europe",
      notes: "Gaulish language.",
    },
    {
      lat: 39.3048,
      lon: 31.2748,
      language: "Celtic",
      region: "Anatolia",
      notes: "Galatian language.",
    },
    {
      lat: 41.4623,
      lon: -5.2719,
      language: "Celtic",
      region: "Iberia",
      notes: "Celtiberian language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Balto-Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula, Britian",
      notes: "",
    },
  ],
  "500AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Eastern Europe, Middle East",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Italo-Dalmantian",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 42.1217,
      lon: 27.1934,
      language: "Italic",
      region: "Southern Europe, Anatolia",
      notes: "Lste Latin",
    },
    {
      lat: 43.0118,
      lon: -0.1547,
      language: "Italic",
      region: "Gaul, Iberia",
      notes: "Western Romance",
    },
    {
      lat: 43.3408,
      lon: 23.2006,
      language: "Italic",
      region: "Eastern Europe, Southern Europe",
      notes: "Eastern Romance",
    },
    {
      lat: 46.3313,
      lon: 15.55,
      language: "Italic",
      region: "Southern Europe",
      notes: "Panonian Romance",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe, Southern Europe, Iberia, Africa",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Gaulish language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe, Central Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 55.0006,
      lon: 23.3424,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Ancestor to all Baltic languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Northern Finnic Languages",
    },
    {
      lat: 57.1918,
      lon: 28.5447,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Southern Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula, Britian",
      notes: "",
    },
  ],
  "600AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Eastern Europe",
      notes: "Koine",
    },
    {
      lat: 39.3942,
      lon: 36.3341,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Ancient Cappadocian",
    },
    {
      lat: 36.2303,
      lon: 33.2829,
      language: "Anatolian",
      region: "Anatolia",
      notes: "Isaurian",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Italo-Dalmantian",
    },
    {
      lat: 44.483,
      lon: 4.4223,
      language: "Italic",
      region:
        "Italy, Gaul, Central Europe, Iberia, Eastern Europe, Southern Europe, Anatolia, Africa, Britian",
      notes: "Vulgar Latin",
    },
    {
      lat: 42.1217,
      lon: 27.1934,
      language: "Italic",
      region: "Southern Europe, Anatolia",
      notes: "Late Latin",
    },
    {
      lat: 43.0118,
      lon: -0.1547,
      language: "Italic",
      region: "Gaul, Iberia",
      notes: "Western Romance",
    },
    {
      lat: 43.3408,
      lon: 23.2006,
      language: "Italic",
      region: "Eastern Europe, Southern Europe",
      notes: "Eastern Romance",
    },
    {
      lat: 46.3313,
      lon: 15.55,
      language: "Italic",
      region: "Southern Europe",
      notes: "Panonian Romance",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 51.3102,
      lon: 11.261,
      language: "Germanic",
      region: "Central Europe",
      notes: "Elbe Germanic Lanuages",
    },
    {
      lat: 53.5623,
      lon: 8.3001,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "North Sea Germanic Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Weser-Rhine Germanic Lanuages",
    },
    {
      lat: 53.0556,
      lon: 15.333,
      language: "Germanic",
      region: "Central Europe, Eastern Europe, Southern Europe, Iberia, Africa",
      notes: "Gothic Languages",
    },
    {
      lat: 56.5639,
      lon: 14.1144,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Gaulish language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe, Central Europe, Southern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 54.3613,
      lon: 21.4004,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Western Baltic languages.",
    },
    {
      lat: 55.3444,
      lon: 25.064,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Eastern Baltic languages.",
    },
    {
      lat: 56.0015,
      lon: 34.0503,
      language: "Baltic",
      region: "Eastern Europe",
      notes: "Dniepr languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Northern Finnic Languages",
    },
    {
      lat: 57.1918,
      lon: 28.5447,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Southern Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula",
      notes: "",
    },
  ],
  "700AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Eastern Europe",
      notes: "Koine",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Italo-Dalmantian",
    },
    {
      lat: 42.1217,
      lon: 27.1934,
      language: "Italic",
      region: "Europe",
      notes: "Medieval Latin",
    },
    {
      lat: 45.4222,
      lon: 2.3952,
      language: "Italic",
      region: "Gaul",
      notes: "Gallo-Romance",
    },
    {
      lat: 39.3525,
      lon: -4.4545,
      language: "Italic",
      region: "Iberia",
      notes: "Iberian Romance",
    },
    {
      lat: 44.29,
      lon: 25.0135,
      language: "Italic",
      region: "Eastern Europe",
      notes: "Proto-Romanian",
    },
    {
      lat: 46.3313,
      lon: 15.55,
      language: "Italic",
      region: "Southern Europe",
      notes: "Panonian Romance",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 53.0555,
      lon: 11.3932,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Saxon",
    },
    {
      lat: 48.265,
      lon: 13.1328,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old High German",
    },
    {
      lat: 52.3207,
      lon: 1.3315,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "Anglo-Frisian Lanuages",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Low Franconian",
    },
    {
      lat: 38.3047,
      lon: -3.3127,
      language: "Germanic",
      region: "Central Europe, Eastern Europe, Southern Europe, Iberia, Africa",
      notes: "Gothic Languages",
    },
    {
      lat: 55.2657,
      lon: 11.3002,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Norse",
    },
    {
      lat: 52.4125,
      lon: -1.2001,
      language: "Celtic",
      region: "Britian",
      notes: "Common Brythonic languages.",
    },
    {
      lat: 56.474,
      lon: -4.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish language.",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Goidelic languages.",
    },
    {
      lat: 47.243,
      lon: 3.5302,
      language: "Celtic",
      region: "Gaul",
      notes: "Gaulish language.",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe, Central Europe, Southern Europe",
      notes: "Ancestor to all Slavic languages.",
    },
    {
      lat: 54.3613,
      lon: 21.4004,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Western Baltic languages.",
    },
    {
      lat: 55.3444,
      lon: 25.064,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Eastern Baltic languages.",
    },
    {
      lat: 56.0015,
      lon: 34.0503,
      language: "Baltic",
      region: "Eastern Europe",
      notes: "Dniepr languages.",
    },
    {
      lat: 58.5106,
      lon: 34.3848,
      language: "Uralic",
      region: "Eastern Europe, Northern Europe",
      notes: "Ancestor of the Northern Finnic Languages",
    },
    {
      lat: 57.1918,
      lon: 28.5447,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Ancestor of the Southern Finnic Languages",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula",
      notes: "",
    },
  ],
  "800AD": [
    {
      lat: 36.5816,
      lon: 22.4305,
      language: "Hellenic",
      region: "Balkans, Sicilly",
      notes: "Doric",
    },
    {
      lat: 38.0412,
      lon: 24.3103,
      language: "Hellenic",
      region: "Balkans, Anatolian, Italy, Eastern Europe",
      notes: "Koine",
    },
    {
      lat: 41.54,
      lon: 12.29,
      language: "Italic",
      region: "Italy",
      notes: "Italo-Dalmantian",
    },
    {
      lat: 42.1217,
      lon: 27.1934,
      language: "Italic",
      region: "Europe",
      notes: "Medieval Latin",
    },
    {
      lat: 45.4222,
      lon: 2.3952,
      language: "Italic",
      region: "Gaul",
      notes: "Gallo-Romance",
    },
    {
      lat: 39.3525,
      lon: -4.4545,
      language: "Italic",
      region: "Iberia",
      notes: "Iberian Romance",
    },
    {
      lat: 44.29,
      lon: 25.0135,
      language: "Italic",
      region: "Eastern Europe",
      notes: "Romanian",
    },
    {
      lat: 41.4617,
      lon: 20.5221,
      language: "Italic",
      region: "Eastern Europe",
      notes: "Aromanian",
    },
    {
      lat: 46.3313,
      lon: 15.55,
      language: "Italic",
      region: "Southern Europe",
      notes: "Panonian Romance",
    },
    {
      lat: 40.083,
      lon: 8.5748,
      language: "Italic",
      region: "Sardinian",
      notes: "Sardinia",
    },
    {
      lat: 34.5814,
      lon: 2.0841,
      language: "Italic",
      region: "Africa",
      notes: "African Romance",
    },
    {
      lat: 53.0555,
      lon: 11.3932,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Saxon",
    },
    {
      lat: 48.265,
      lon: 13.1328,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old High German",
    },
    {
      lat: 52.3207,
      lon: 1.3315,
      language: "Germanic",
      region: "Central Europe, Britian",
      notes: "Old English",
    },
    {
      lat: 53.381,
      lon: 7.262,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Frisian",
    },
    {
      lat: 51.1701,
      lon: 6.2138,
      language: "Germanic",
      region: "Central Europe",
      notes: "Old Low Franconian",
    },
    {
      lat: 45.2648,
      lon: 34.3536,
      language: "Germanic",
      region: "Eastern Europe",
      notes: "Crimean Gothic",
    },
    {
      lat: 59.3822,
      lon: 7.5959,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old West Norse",
    },
    {
      lat: 57.3802,
      lon: 18.362,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old Gutnish",
    },
    {
      lat: 55.2657,
      lon: 11.3002,
      language: "Germanic",
      region: "Northern Europe",
      notes: "Old East Norse",
    },
    {
      lat: 57.474,
      lon: -3.154,
      language: "Celtic",
      region: "North Britian",
      notes: "Pictish",
    },
    {
      lat: 53.4439,
      lon: -8.1054,
      language: "Celtic",
      region: "Ireland",
      notes: "Irish",
    },
    {
      lat: 48.0833,
      lon: -3.3056,
      language: "Celtic",
      region: "Brittany",
      notes: "Breton",
    },
    {
      lat: 50.4829,
      lon: -3.4531,
      language: "Celtic",
      region: "Cornwall",
      notes: "Cornish",
    },
    {
      lat: 52.3511,
      lon: -3.2041,
      language: "Celtic",
      region: "Wales",
      notes: "Welsh",
    },
    {
      lat: 54.2338,
      lon: -2.5716,
      language: "Celtic",
      region: "Crumbria",
      notes: "Cumbric",
    },
    {
      lat: 56.2523,
      lon: -5.595,
      language: "Celtic",
      region: "North Britian",
      notes: "Scottish Gaelic",
    },
    {
      lat: 54.1359,
      lon: -4.3508,
      language: "Celtic",
      region: "Mann",
      notes: "Manx",
    },
    {
      lat: 51.0519,
      lon: 26.1433,
      language: "Slavic",
      region: "Eastern Europe",
      notes: "East Slavic languages.",
    },
    {
      lat: 51.5227,
      lon: 19.0904,
      language: "Slavic",
      region: "Central Europe",
      notes: "West Slavic languages.",
    },
    {
      lat: 43.452,
      lon: 23.0842,
      language: "Slavic",
      region: "Southern Europe",
      notes: "South Slavic languages.",
    },
    {
      lat: 54.3613,
      lon: 21.4004,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Western Baltic languages.",
    },
    {
      lat: 55.3444,
      lon: 25.064,
      language: "Baltic",
      region: "Baltic Europe",
      notes: "Eastern Baltic languages.",
    },
    {
      lat: 56.0015,
      lon: 34.0503,
      language: "Baltic",
      region: "Eastern Europe",
      notes: "Dniepr languages.",
    },
    {
      lat: 60.2943,
      lon: 24.0434,
      language: "Uralic",
      region: "Northern Europe",
      notes: "Finnish",
    },
    {
      lat: 62.0607,
      lon: 32.2222,
      language: "Uralic",
      region: "Northern Europe",
      notes: "Karelian",
    },
    {
      lat: 57.1918,
      lon: 28.5447,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Estonian",
    },
    {
      lat: 57.0457,
      lon: 22.3607,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Livonian",
    },
    {
      lat: 47.0626,
      lon: 48.2545,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Hungarian",
    },
    {
      lat: 55.2303,
      lon: 47.1538,
      language: "Uralic",
      region: "Eastern Europe",
      notes: "Mordvinic",
    },
    {
      lat: 43.3912,
      lon: 41.5434,
      language: "Paleo-European",
      region: "Eastern Europe",
      notes: "",
    },
    {
      lat: 42.3649,
      lon: -0.595,
      language: "Paleo-European",
      region: "Iberian Peninsula",
      notes: "",
    },
  ],
};

// Map of language to color
const languageColorMap = {
  Latin: "blue",
  Italic: "blue",
  Celtic: "green",
  Germanic: "red",
  Iberian: "purple",
  Slavic: "yellow",
  Baltic: "orange",
  Lusitanian: "purple",
  Anatolian: "brown",
  Hellenic: "teal",
  Uralic: "turquoise",
  PaleoEuropean: "grey",
};

// Function to create a marker with a custom color based on the language
function getLanguageMarkerColor(language) {
  return languageColorMap[language] || "gray"; // Default to gray if the language is not in the map
}

// Function to load language data and display markers with different colors
function loadLanguageData(year) {
  // Clear any existing markers on the map
  map.eachLayer((layer) => {
    if (layer instanceof L.Marker || layer instanceof L.CircleMarker) {
      map.removeLayer(layer); // Remove all markers (both L.Marker and L.CircleMarker)
    }
  });

  // Load markers for the selected year
  const markers = markersData[year]; // Get the markers for the selected year

  markers.forEach((marker) => {
    const markerColor = getLanguageMarkerColor(marker.language); // Get the color based on the language

    // Create a circle marker with the color based on the language
    L.circleMarker([marker.lat, marker.lon], {
      color: markerColor,
      fillColor: markerColor,
      fillOpacity: 0.5,
      radius: 8, // Size of the marker
    })
      .addTo(map)
      .bindPopup(
        `<b>${marker.language}</b><br>${marker.region}<br>${marker.notes}`
      );
  });
}

const languageFamilyDetails = {
  Hellenic: `<strong>Languages:</strong> Greek<br>
    <strong>Geographical Area:</strong> Greece, Cyprus, and parts of the Aegean.<br>
    <strong>Extinct Languages:</strong> Mycenaean Greek, Ancient Greek (Classical, Koine).<br>
    <strong>Endangered Languages:</strong> Tsakonian (a modern Greek dialect).<br>
    <strong>Historical Context:</strong>
    The Hellenic family, dominated by Greek, has a documented history spanning over 3,500 years. Mycenaean Greek was used in the early Greek city-states. Ancient Greek developed into Classical and Koine forms, the latter serving as a lingua franca in the Hellenistic world. Modern Greek retains ties to its ancient predecessors.<br>
    <strong>Notes:</strong> The Hellenic language family is centered around Greek, with its history stretching back thousands of years. Ancient Greek was the language of classical philosophy, science, and literature, while modern Greek remains the official language of Greece and Cyprus.`,
  Anatolian: `<strong>Languages:</strong> Hittite, Luwian, Lydian, Lycian, and others [All extinct]<br>
    <strong>Geographical Area:</strong> Anatolia (modern-day Turkey)<br>
    <strong>Extinct Languages:</strong> Hittite, Luwian, Lycian, Lydian.<br>
    <strong>Endangered Languages:</strong> None, as the family is entirely extinct.<br>
    <strong>Historical Context:</strong>
    Anatolian languages were spoken in ancient Turkey and were among the first written Indo-European languages, with records dating back to the 2nd millennium BCE. The Hittite Empire was a major power in the ancient Near East. Anatolian languages disappeared around the 1st millennium BCE, replaced by Greek and other languages.<br>
    <strong>Notes:</strong> The Anatolian languages are an extinct branch of the Indo-European family, with the Hittite language being the most famous. The Hittites were an ancient civilization in the Near East.`,
  Celtic: `<strong>Languages:</strong> Irish, Scottish Gaelic, Welsh, Breton, Cornish, Manx<br>
    <strong>Geographical Area:</strong> Western Europe, particularly the British Isles, France (Brittany), and parts of Spain<br>
    <strong>Extinct Languages:</strong> Gaulish, Lepontic, Celtiberian, Pictish.<br>
    <strong>Endangered Languages:</strong> Cornish (revived), Manx (revived), Breton.<br>
    <strong>Historical Context:</strong>
    The Celtic language family once spread widely across Europe, from Iberia to Anatolia. It fragmented after Roman conquest and Germanic invasions. Today, Celtic languages are mainly confined to the British Isles and Brittany, France. Revival efforts in Cornwall and the Isle of Man have brought renewed interest in these languages.<br>
    <strong>Notes:</strong> The Celtic languages are characterized by unique syntactical and phonological features. The ancient Celts were known for their tribal societies, which later contributed to the formation of various European kingdoms.`,
  Germanic: `<strong>Languages:</strong> English, German, Dutch, Swedish, Danish, Norwegian, Icelandic, and others<br>
    <strong>Geographical Area:</strong> Northern and Western Europe, especially the UK, Germany, Scandinavia, and the Low Countries<br>
    <strong>Extinct Languages:</strong> Gothic, Vandalic, Burgundian.<br>
    <strong>Endangered Languages:</strong> Yiddish (partially), Scots (debated), Low German.<br>
    <strong>Historical Context:</strong>
    Originating from Proto-Germanic, the family split into East, North, and West Germanic branches. East Germanic languages, like Gothic, are extinct. Modern Germanic languages include some of the world's most spoken, such as English and German. Historically, Germanic tribes shaped medieval Europe after the fall of the Roman Empire.<br>
    <strong>Notes:</strong> The Germanic family is one of the most widely spoken language families globally. English, as a Germanic language, has become a global lingua franca, heavily influenced by Latin and French.`,
  Italic: `<strong>Languages:</strong> Latin, Italian, Spanish, French, Portuguese, Romanian, and others<br>
    <strong>Geographical Area:</strong> Southern and Western Europe, the Mediterranean, and parts of Eastern Europe<br>
    <strong>Extinct Languages:</strong> Latin (Classical and Vulgar), Oscan, Umbrian, Faliscan.<br>
    <strong>Endangered Languages:</strong> Ladin, Friulian, Romansh.<br>
    <strong>Historical Context:</strong>
    The Italic family dominated the Italian Peninsula and was crucial for the rise of the Roman Empire. Latin evolved into the Romance languages, such as Italian, Spanish, and French. While Latin is no longer spoken natively, it remains influential as the language of science, law, and the Catholic Church.<br>
    <strong>Notes:</strong> The Italic family includes the Romance languages, which evolved from Vulgar Latin. Latin was the language of the Roman Empire and continues to influence legal, religious, and scientific terms.`,
  Baltic: `<strong>Languages:</strong> Lithuanian, Latvian<br>
    <strong>Geographical Area:</strong> The Baltic region, particularly Lithuania and Latvia<br>
    <strong>Extinct Languages:</strong> Old Prussian, Curonian, Selonian, Semigallian.<br>
    <strong>Endangered Languages:</strong> None currently, but both Latvian and Lithuanian have relatively small speaker populations.<br>
    <Strong>Historical Context:</strong>
    Baltic languages were historically spoken over a much larger area in Eastern Europe but diminished due to Slavic expansion. Old Prussian, once spoken in modern-day Poland, became extinct in the 17th century. Lithuanian, the most conservative Indo-European language, retains many ancient features.<br>
    <strong>Notes:</strong> The Baltic languages are considered one of the oldest and most conservative Indo-European languages. Lithuanian and Latvian retain many archaic features of the Proto-Indo-European language.`,
  Slavic: `<strong>Languages:</strong> Russian, Polish, Czech, Slovak, Ukrainian, Bulgarian, Serbian, Croatian, and others<br>
    <strong>Geographical Area:</strong> Eastern Europe, the Balkans, and parts of Central Europe<br>
    <strong>Extinct Languages:</strong> Polabian, Old Church Slavonic (as a vernacular).<br>
    <strong>Endangered Languages:</strong> Kashubian, Sorbian (Upper and Lower).<br>
    <strong>Historical Context:</strong>
    Slavic languages developed from Proto-Slavic and expanded widely through migrations. They are divided into East, West, and South Slavic branches. Historically, Old Church Slavonic was the liturgical language of the Orthodox Church and helped preserve early Slavic texts.<br>
    <strong>Notes:</strong> Slavic languages are divided into three subgroups: East Slavic (e.g., Russian), West Slavic (e.g., Polish), and South Slavic (e.g., Bulgarian). They have a rich literary tradition and have been heavily influenced by the Orthodox and Catholic churches.`,
  Lusitanian: `<strong>Languages:</strong> Ancient Lusitanian [Extinct]<br>
    <strong>Geographical Area:</strong> Western Iberian Peninsula (modern Portugal and parts of Spain)<br>
    <strong>Extinct Languages:</strong> Lusitanian (the only known language of the family).<br>
    <strong>Endangered Languages:</strong> None, as the family is entirely extinct.<br>
    <strong>Historical Context:</strong>
    Lusitanian was spoken in parts of modern Portugal and western Spain during the Iron Age. Its classification is debated, as some linguists consider it a pre-Indo-European isolate. Little is known about its grammar and vocabulary due to limited inscriptions.<br>
    <strong>Notes:</strong> The Lusitanian language is an extinct language from the Iberian Peninsula, historically spoken by the Lusitanians. It is not fully understood and has left few records.`,
  Uralic: `<strong>Languages:</strong> Finnish, Hungarian, Estonian, and others<br>
    <strong>Geographical Area:</strong> Eastern Europe, Northern Europe, and parts of Siberia<br>
    <strong>Extinct Languages:</strong> Kamassian, Merya, Muromian.<br>
    <strong>Endangered Languages:</strong> Votic, Livonian, Udmurt, Komi.<br>
    <strong>Historical Context:</strong>
    Uralic languages originated in the Ural Mountains and spread across northern Eurasia. They include Finno-Ugric and Samoyedic branches. Some, like Finnish and Hungarian, are vibrant, while others face extinction due to assimilation and declining populations. Livonian, for example, is critically endangered.<br>
    <strong>Notes:</strong> The Uralic languages are distinct from the Indo-European family, with Finnish and Hungarian being the most well-known. They are spoken by ethnic groups in Finland, Hungary, and across Northern Eurasia.`,
  PaleoEuropean: `<strong>Languages:</strong> Pre-Indo-European languages<br>
    <strong>Geographical Area:</strong> Europe, before the spread of Indo-European languages<br>
    <strong>Extinct Languages:</strong> Aquitanian, Tartessian, Etruscan.<br>
    <strong>Endangered Languages:</strong> Basque (possibly the last surviving Paleo-European language).<br>
    <strong>Historical Context:</strong>
    Paleo-European languages are pre-Indo-European languages once spoken across Europe. Etruscan, spoken in ancient Italy, was a sophisticated language tied to the early Roman Republic. Basque, spoken in Spain and France, is a linguistic isolate and possibly the last remnant of these ancient languages.<br>
    <strong>Notes:</strong> The Paleo-European languages are the prehistoric languages of Europe that were spoken before the arrival of the Indo-European languages. These languages are poorly understood and are mostly lost to history.`,
};

// Reference to the details box
const detailsBox = document.getElementById("languageDetails");

// Event listener for legend clicks
document.getElementById("legend").addEventListener("click", (event) => {
  // Ensure the clicked element is a legend button
  const button = event.target.closest("button"); // Use closest() to ensure it's a button
  if (!button) return; // Exit if a button wasn't clicked

  // Get the language family from the button's data attribute
  const languageFamily = button.getAttribute("data-language-family");
  if (languageFamily && languageFamilyDetails[languageFamily]) {
    // Display details in the details box
    detailsBox.innerHTML = `<h3>${languageFamily}</h3><p>${languageFamilyDetails[languageFamily]}</p>`;
  }
});

// Get slider and year label elements
const slider = document.getElementById("timeSlider");
const yearLabel = document.getElementById("yearLabel");
const playButton = document.getElementById("playButton");

let intervalId; // To store the interval ID
let isPlaying = false; // To track if the play button is active

// Set the slider's max value to 5 to match the years in yearMap
slider.max = 17;

// Event listener for the slider input
slider.addEventListener("input", (event) => {
  const yearKey = yearMap[event.target.value];
  yearLabel.textContent = yearKey.replace("BC", " BC").replace("AD", " AD");
  loadLanguageData(yearKey); // Load the markers for the selected year
});

// Event listener for the Play button
playButton.addEventListener("click", () => {
  if (isPlaying) {
    clearInterval(intervalId); // Stop the interval if it's running
    playButton.textContent = "Play"; // Change button text back to "Play"
    isPlaying = false;
  } else {
    isPlaying = true;
    playButton.textContent = "Pause"; // Change button text to "Pause"

    let currentValue = parseInt(slider.value); // Get the current slider value
    const maxValue = parseInt(slider.max); // Get the maximum slider value

    intervalId = setInterval(() => {
      if (currentValue <= maxValue) {
        const yearKey = yearMap[currentValue];
        yearLabel.textContent = yearKey
          .replace("BC", " BC")
          .replace("AD", " AD");
        loadLanguageData(yearKey); // Load the markers for the current year
        slider.value = currentValue; // Update the slider to match
        currentValue += 1; // Move to the next year
      } else {
        clearInterval(intervalId); // Stop the interval when the max is reached
        playButton.textContent = "Play"; // Reset the button text
        isPlaying = false;
      }
    }, 2000); // Change year every 2 seconds (adjust as needed)
  }
});

// Initial load for 2500 BC
loadLanguageData("2500BC");
